/* Test próbny w formacie egzaminu (pytania ułożone przez autora strony na podstawie wykładów).
   Każde pytanie: 4 odpowiedzi, poprawnych 1–4. Teksty w trzech językach. */
(function (SBD) {
  'use strict';

  function A(ok, pl, en, ru) { return { ok: !!ok, pl: pl, en: en, ru: ru }; }
  function T(pl, en, ru) { return { pl: pl, en: en, ru: ru }; }

  SBD.quiz = [
    { t: 'relational-model',
      q: T('Które zdania o relacji w modelu relacyjnym są prawdziwe?', 'Which statements about a relation in the relational model are true?', 'Какие утверждения об отношении в реляционной модели верны?'),
      a: [A(1, 'Relacja to podzbiór iloczynu kartezjańskiego.', 'A relation is a subset of a Cartesian product.', 'Отношение — это подмножество декартова произведения.'),
          A(1, 'Wynik polecenia SELECT też jest relacją.', 'The result of a SELECT is also a relation.', 'Результат SELECT — тоже отношение.'),
          A(0, 'Baza jest „relacyjna”, bo tabele łączą relacje (klucze obce).', 'A database is "relational" because tables are linked by relations (foreign keys).', 'База «реляционная», потому что таблицы соединены отношениями (внешними ключами).'),
          A(0, 'Iloczyn kartezjański jest przemienny: A×B = B×A.', 'The Cartesian product is commutative: A×B = B×A.', 'Декартово произведение коммутативно: A×B = B×A.')],
      e: T('Nazwa pochodzi od relacji = tabeli (podzbioru iloczynu kartezjańskiego). Połączenia tabel to związki. A×B ≠ B×A.', 'The name comes from relation = table (a subset of a Cartesian product). Links between tables are relationships. A×B ≠ B×A.', 'Название — от отношения = таблицы (подмножества декартова произведения). Связи таблиц — это «związki». A×B ≠ B×A.') },

    { t: 'relational-model',
      q: T('Które wyrażenia mają wartość TRUE?', 'Which expressions evaluate to TRUE?', 'Какие выражения равны TRUE?'),
      a: [A(1, 'NULL OR TRUE', 'NULL OR TRUE', 'NULL OR TRUE'),
          A(0, 'NULL = NULL', 'NULL = NULL', 'NULL = NULL'),
          A(0, 'NOT NULL', 'NOT NULL', 'NOT NULL'),
          A(0, 'NULL AND FALSE', 'NULL AND FALSE', 'NULL AND FALSE')],
      e: T('NULL = NULL i NOT NULL dają NULL; NULL AND FALSE = FALSE. Tylko NULL OR TRUE = TRUE.', 'NULL = NULL and NOT NULL give NULL; NULL AND FALSE = FALSE. Only NULL OR TRUE = TRUE.', 'NULL = NULL и NOT NULL дают NULL; NULL AND FALSE = FALSE. Только NULL OR TRUE = TRUE.') },

    { t: 'relational-model',
      q: T('Klucz główny (PRIMARY KEY):', 'A primary key:', 'Первичный ключ (PRIMARY KEY):'),
      a: [A(1, 'musi mieć unikalne wartości,', 'must have unique values,', 'должен иметь уникальные значения,'),
          A(1, 'nie może zawierać NULL,', 'cannot contain NULL,', 'не может содержать NULL,'),
          A(0, 'może występować w tabeli kilka razy,', 'may appear several times in a table,', 'может быть в таблице несколько раз,'),
          A(1, 'może składać się z kilku kolumn.', 'may consist of several columns.', 'может состоять из нескольких столбцов.')],
      e: T('PK: unikalność + brak NULL; jeden na tabelę; może być złożony.', 'PK: uniqueness + no NULL; one per table; may be composite.', 'PK: уникальность + нет NULL; один на таблицу; может быть составным.') },

    { t: 'relational-model',
      q: T('Więzy UNIQUE:', 'UNIQUE constraints:', 'Ограничение UNIQUE:'),
      a: [A(1, 'w MS SQL Server dopuszczają tylko jeden NULL w kolumnie,', 'in MS SQL Server allow only one NULL in the column,', 'в MS SQL Server допускают только один NULL в столбце,'),
          A(1, 'w Oracle dopuszczają wiele wartości NULL,', 'in Oracle allow many NULL values,', 'в Oracle допускают много NULL,'),
          A(0, 'są tym samym co PRIMARY KEY,', 'are the same as PRIMARY KEY,', 'это то же самое, что PRIMARY KEY,'),
          A(1, 'są realizowane przez utworzenie indeksu.', 'are implemented by creating an index.', 'реализуются созданием индекса.')],
      e: T('Teoria dopuszcza NULL w UNIQUE; Oracle to realizuje, MS SQL traktuje NULL jak wartość (tylko jeden). Realizacją UNIQUE jest indeks.', 'Theory allows NULL in UNIQUE; Oracle follows it, MS SQL treats NULL as a value (only one). UNIQUE is implemented by an index.', 'Теория допускает NULL в UNIQUE; Oracle так и делает, MS SQL считает NULL значением (только один). UNIQUE реализуется индексом.') },

    { t: 'erd',
      q: T('Związek wiele-do-wielu (M:N) w modelu relacyjnym:', 'A many-to-many (M:N) relationship in the relational model:', 'Связь многие-ко-многим (M:N) в реляционной модели:'),
      a: [A(1, 'realizujemy przez encję (tabelę) asocjacyjną,', 'is implemented with an associative entity (table),', 'реализуется через ассоциативную сущность (таблицу),'),
          A(1, 'klucz encji asocjacyjnej to suma kluczy łączonych encji,', 'the key of the associative entity is the sum of the keys of the linked entities,', 'ключ ассоциативной сущности — сумма ключей связываемых сущностей,'),
          A(0, 'związki z encją asocjacyjną są nieidentyfikujące,', 'relationships to the associative entity are non-identifying,', 'связи с ассоциативной сущностью неидентифицирующие,'),
          A(0, 'da się zapisać bezpośrednio jednym kluczem obcym.', 'can be stored directly with one foreign key.', 'можно записать напрямую одним внешним ключом.')],
      e: T('Encja asocjacyjna jest zależna — związki są identyfikujące (FK wchodzą do PK).', 'The associative entity is dependent — the relationships are identifying (FKs are part of the PK).', 'Ассоциативная сущность зависимая — связи идентифицирующие (FK входят в PK).') },

    { t: 'erd',
      q: T('Związek rekurencyjny (np. EMP.MGR → EMP.EMPNO):', 'A recursive relationship (e.g. EMP.MGR → EMP.EMPNO):', 'Рекурсивная связь (напр. EMP.MGR → EMP.EMPNO):'),
      a: [A(1, 'musi być opcjonalny (FK dopuszcza NULL),', 'must be optional (FK allows NULL),', 'должна быть необязательной (FK допускает NULL),'),
          A(1, 'nie może być identyfikujący,', 'cannot be identifying,', 'не может быть идентифицирующей,'),
          A(1, 'łączy tabelę z nią samą,', 'links a table with itself,', 'связывает таблицу с самой собой,'),
          A(0, 'wymaga tabeli asocjacyjnej.', 'requires an associative table.', 'требует ассоциативной таблицы.')],
      e: T('Bez NULL nie wstawimy pierwszego wiersza (prezes nie ma szefa). Tabela asocjacyjna jest potrzebna tylko dla M:N.', 'Without NULL we cannot insert the first row (the CEO has no boss). An associative table is only for M:N.', 'Без NULL не вставить первую строку (у директора нет начальника). Ассоциативная таблица нужна только для M:N.') },

    { t: 'normalization',
      q: T('OCENA {NrIndeksu, KodPrzedmiotu, Ocena, Wykladowca}, klucz (NrIndeksu, KodPrzedmiotu), zachodzi KodPrzedmiotu → Wykladowca. Co jest prawdą?', 'OCENA {NrIndeksu, KodPrzedmiotu, Ocena, Wykladowca}, key (NrIndeksu, KodPrzedmiotu), and KodPrzedmiotu → Wykladowca holds. What is true?', 'OCENA {NrIndeksu, KodPrzedmiotu, Ocena, Wykladowca}, ключ (NrIndeksu, KodPrzedmiotu), выполняется KodPrzedmiotu → Wykladowca. Что верно?'),
      a: [A(1, 'Tabela nie jest w 2NF.', 'The table is not in 2NF.', 'Таблица не в 2NF.'),
          A(0, 'Dodanie sztucznego klucza IdOcena jako PK rozwiązuje problem.', 'Adding a surrogate key IdOcena as PK solves the problem.', 'Добавление искусственного ключа IdOcena как PK решает проблему.'),
          A(1, 'Rozwiązanie: przenieść Wykladowca do tabeli PRZEDMIOT.', 'Solution: move Wykladowca to the PRZEDMIOT table.', 'Решение: перенести Wykladowca в таблицу PRZEDMIOT.'),
          A(0, 'To zależność przechodnia.', 'It is a transitive dependency.', 'Это транзитивная зависимость.')],
      e: T('To zależność częściowa (od części klucza) → brak 2NF. Sztuczny klucz nic nie zmienia — (NrIndeksu, KodPrzedmiotu) dalej jest kluczem.', 'It is a partial dependency (on part of the key) → no 2NF. A surrogate key changes nothing — (NrIndeksu, KodPrzedmiotu) is still a key.', 'Это частичная зависимость (от части ключа) → нет 2NF. Искусственный ключ ничего не меняет — (NrIndeksu, KodPrzedmiotu) остаётся ключом.') },

    { t: 'normalization',
      q: T('3NF i BCNF:', '3NF and BCNF:', '3NF и BCNF:'),
      a: [A(1, '3NF dopuszcza X → A, gdy A jest atrybutem kluczowym (choć X nie jest nadkluczem),', '3NF allows X → A when A is a key attribute (even if X is not a superkey),', '3NF допускает X → A, если A — ключевой атрибут (даже если X не суперключ),'),
          A(1, 'każda tabela w BCNF jest w 3NF,', 'every table in BCNF is in 3NF,', 'любая таблица в BCNF находится в 3NF,'),
          A(0, 'każda tabela w 3NF jest w BCNF,', 'every table in 3NF is in BCNF,', 'любая таблица в 3NF находится в BCNF,'),
          A(1, 'w praktyce doprowadzamy bazę co najmniej do 3NF.', 'in practice we normalize at least to 3NF.', 'на практике приводим базу как минимум к 3NF.')],
      e: T('BCNF jest ostrzejsza. Są tabele, których nie da się doprowadzić do BCNF bez utraty informacji — dlatego istnieje 3NF.', 'BCNF is stricter. Some tables cannot reach BCNF without losing information — hence 3NF.', 'BCNF строже. Некоторые таблицы нельзя привести к BCNF без потери информации — поэтому есть 3NF.') },

    { t: 'select-basics',
      q: T('Pracownik ma sal = 1000 i comm = NULL. Co zwróci 12*sal + comm?', 'An employee has sal = 1000 and comm = NULL. What does 12*sal + comm return?', 'У сотрудника sal = 1000 и comm = NULL. Что вернёт 12*sal + comm?'),
      a: [A(1, 'NULL', 'NULL', 'NULL'),
          A(0, '12000', '12000', '12000'),
          A(0, 'błąd wykonania', 'a runtime error', 'ошибку выполнения'),
          A(0, '0', '0', '0')],
      e: T('Każde działanie z NULL daje NULL. Poprawnie: 12*sal + NVL(comm, 0) / ISNULL(comm, 0).', 'Any arithmetic with NULL gives NULL. Correct: 12*sal + NVL(comm, 0) / ISNULL(comm, 0).', 'Любая арифметика с NULL даёт NULL. Правильно: 12*sal + NVL(comm, 0) / ISNULL(comm, 0).') },

    { t: 'select-basics',
      q: T('Które wyrażenia zwrócą 0, gdy comm jest NULL?', 'Which expressions return 0 when comm is NULL?', 'Какие выражения вернут 0, если comm = NULL?'),
      a: [A(1, 'NVL(comm, 0) w Oracle', 'NVL(comm, 0) in Oracle', 'NVL(comm, 0) в Oracle'),
          A(1, 'ISNULL(comm, 0) w MS SQL', 'ISNULL(comm, 0) in MS SQL', 'ISNULL(comm, 0) в MS SQL'),
          A(1, 'COALESCE(comm, 0)', 'COALESCE(comm, 0)', 'COALESCE(comm, 0)'),
          A(0, 'comm = NULL', 'comm = NULL', 'comm = NULL')],
      e: T('comm = NULL to porównanie, które daje NULL, a nie 0.', 'comm = NULL is a comparison giving NULL, not 0.', 'comm = NULL — это сравнение, дающее NULL, а не 0.') },

    { t: 'group-by',
      q: T('Tabela EMP ma 14 wierszy, a kolumna comm 4 wartości różne od NULL. Co jest prawdą?', 'EMP has 14 rows and column comm has 4 non-NULL values. What is true?', 'В EMP 14 строк, а в столбце comm 4 значения не NULL. Что верно?'),
      a: [A(1, 'COUNT(*) = 14', 'COUNT(*) = 14', 'COUNT(*) = 14'),
          A(1, 'COUNT(comm) = 4', 'COUNT(comm) = 4', 'COUNT(comm) = 4'),
          A(0, 'COUNT(1) = 4', 'COUNT(1) = 4', 'COUNT(1) = 4'),
          A(0, 'COUNT(comm) = 14', 'COUNT(comm) = 14', 'COUNT(comm) = 14')],
      e: T('COUNT(stała) i COUNT(*) liczą wiersze; COUNT(kolumna) — wartości nie-NULL.', 'COUNT(constant) and COUNT(*) count rows; COUNT(column) counts non-NULL values.', 'COUNT(константа) и COUNT(*) считают строки; COUNT(столбец) — значения не NULL.') },

    { t: 'where-joins',
      q: T("Co zwróci: WHERE job = 'CLERK' OR job = 'SALESMAN' AND sal > 1100?", "What does WHERE job = 'CLERK' OR job = 'SALESMAN' AND sal > 1100 return?", "Что вернёт WHERE job = 'CLERK' OR job = 'SALESMAN' AND sal > 1100?"),
      a: [A(1, 'wszystkich CLERK, niezależnie od płacy,', 'all CLERKs regardless of salary,', 'всех CLERK независимо от зарплаты,'),
          A(1, 'SALESMAN-ów zarabiających ponad 1100,', 'SALESMEN earning more than 1100,', 'SALESMAN с зарплатой больше 1100,'),
          A(0, 'tylko CLERK zarabiających ponad 1100,', 'only CLERKs earning more than 1100,', 'только CLERK с зарплатой больше 1100,'),
          A(1, 'wynik wynika z tego, że AND ma wyższy priorytet niż OR.', 'this is because AND has a higher priority than OR.', 'так получается, потому что AND имеет больший приоритет, чем OR.')],
      e: T('To jest CLERK OR (SALESMAN AND sal > 1100). Nawiasy zmieniają kolejność.', 'This means CLERK OR (SALESMAN AND sal > 1100). Parentheses change the order.', 'Это CLERK OR (SALESMAN AND sal > 1100). Скобки меняют порядок.') },

    { t: 'where-joins',
      q: T('Które złączenia pokażą pracownika z deptno = NULL (tabela Emp po lewej stronie)?', 'Which joins will show an employee with deptno = NULL (Emp on the left side)?', 'Какие соединения покажут сотрудника с deptno = NULL (Emp слева)?'),
      a: [A(1, 'Emp LEFT JOIN Dept ON …', 'Emp LEFT JOIN Dept ON …', 'Emp LEFT JOIN Dept ON …'),
          A(0, 'Emp INNER JOIN Dept ON …', 'Emp INNER JOIN Dept ON …', 'Emp INNER JOIN Dept ON …'),
          A(1, 'Emp FULL JOIN Dept ON …', 'Emp FULL JOIN Dept ON …', 'Emp FULL JOIN Dept ON …'),
          A(0, 'Emp RIGHT JOIN Dept ON …', 'Emp RIGHT JOIN Dept ON …', 'Emp RIGHT JOIN Dept ON …')],
      e: T('LEFT i FULL zachowują wszystkie wiersze tabeli z lewej. RIGHT zachowuje wiersze Dept.', 'LEFT and FULL keep all rows of the left table. RIGHT keeps the Dept rows.', 'LEFT и FULL сохраняют все строки левой таблицы. RIGHT сохраняет строки Dept.') },

    { t: 'where-joins',
      q: T('Operatory na zbiorach wyników:', 'Set operators on query results:', 'Операторы над множествами результатов:'),
      a: [A(1, 'UNION usuwa duplikaty,', 'UNION removes duplicates,', 'UNION убирает дубликаты,'),
          A(0, 'UNION ALL usuwa duplikaty,', 'UNION ALL removes duplicates,', 'UNION ALL убирает дубликаты,'),
          A(1, 'w Oracle różnicę zapisuje się jako MINUS,', 'in Oracle the difference is written as MINUS,', 'в Oracle разность записывается как MINUS,'),
          A(1, 'łączone zapytania muszą mieć tyle samo kolumn o zgodnych typach.', 'the combined queries must have the same number of columns of compatible types.', 'объединяемые запросы должны иметь одинаковое число столбцов совместимых типов.')],
      e: T('UNION ALL zostawia powtórzenia. EXCEPT (standard/MS SQL) = MINUS (Oracle).', 'UNION ALL keeps duplicates. EXCEPT (standard/MS SQL) = MINUS (Oracle).', 'UNION ALL оставляет повторы. EXCEPT (стандарт/MS SQL) = MINUS (Oracle).') },

    { t: 'group-by',
      q: T('Zapytanie ma GROUP BY deptno. Co może być na liście SELECT?', 'A query has GROUP BY deptno. What may appear in the SELECT list?', 'В запросе GROUP BY deptno. Что может быть в списке SELECT?'),
      a: [A(1, 'deptno', 'deptno', 'deptno'),
          A(1, 'COUNT(*)', 'COUNT(*)', 'COUNT(*)'),
          A(0, 'ename', 'ename', 'ename'),
          A(1, "stała, np. 'X'", "a constant, e.g. 'X'", "константа, напр. 'X'")],
      e: T('Tylko stałe, agregaty i wyrażenia z GROUP BY. ename da błąd (Msg 8120 / ORA-00979).', 'Only constants, aggregates and GROUP BY expressions. ename causes an error (Msg 8120 / ORA-00979).', 'Только константы, агрегаты и выражения из GROUP BY. ename даст ошибку (Msg 8120 / ORA-00979).') },

    { t: 'group-by',
      q: T('WHERE a HAVING:', 'WHERE vs HAVING:', 'WHERE и HAVING:'),
      a: [A(1, 'funkcji agregujących nie wolno używać w WHERE,', 'aggregate functions are not allowed in WHERE,', 'агрегатные функции нельзя использовать в WHERE,'),
          A(1, 'HAVING filtruje grupy po grupowaniu,', 'HAVING filters groups after grouping,', 'HAVING фильтрует группы после группировки,'),
          A(0, 'WHERE jest wykonywane po HAVING,', 'WHERE is executed after HAVING,', 'WHERE выполняется после HAVING,'),
          A(1, 'warunek deptno <> 10 lepiej umieścić w WHERE niż w HAVING.', 'the condition deptno <> 10 is better placed in WHERE than in HAVING.', 'условие deptno <> 10 лучше поместить в WHERE, чем в HAVING.')],
      e: T('WHERE działa przy odczycie wierszy (wcześniej), HAVING na grupach. Filtruj jak najwcześniej.', 'WHERE works while reading rows (earlier), HAVING on groups. Filter as early as possible.', 'WHERE работает при чтении строк (раньше), HAVING — по группам. Фильтруй как можно раньше.') },

    { t: 'subqueries',
      q: T('SELECT ename FROM emp WHERE empno NOT IN (SELECT mgr FROM emp); — kolumna mgr zawiera NULL (KING). Co jest prawdą?', 'SELECT ename FROM emp WHERE empno NOT IN (SELECT mgr FROM emp); — column mgr contains NULL (KING). What is true?', 'SELECT ename FROM emp WHERE empno NOT IN (SELECT mgr FROM emp); — в mgr есть NULL (KING). Что верно?'),
      a: [A(1, 'Zapytanie zwróci pusty wynik.', 'The query returns an empty result.', 'Запрос вернёт пустой результат.'),
          A(0, 'Zapytanie zwróci pracowników, którzy nie są szefami.', 'The query returns employees who are not bosses.', 'Запрос вернёт сотрудников, которые не начальники.'),
          A(1, 'Pomoże dopisanie WHERE mgr IS NOT NULL w podzapytaniu.', 'Adding WHERE mgr IS NOT NULL to the subquery helps.', 'Поможет добавить WHERE mgr IS NOT NULL в подзапрос.'),
          A(1, 'Wersja z NOT EXISTS działa poprawnie.', 'The NOT EXISTS version works correctly.', 'Версия с NOT EXISTS работает правильно.')],
      e: T('x NOT IN (…, NULL) nigdy nie jest TRUE, bo x <> NULL daje NULL.', 'x NOT IN (…, NULL) is never TRUE because x <> NULL gives NULL.', 'x NOT IN (…, NULL) никогда не TRUE, так как x <> NULL даёт NULL.') },

    { t: 'subqueries',
      q: T('Kwantyfikatory ALL i ANY/SOME:', 'Quantifiers ALL and ANY/SOME:', 'Кванторы ALL и ANY/SOME:'),
      a: [A(1, 'sal >= ALL (podzapytanie) oznacza porównanie z maksimum,', 'sal >= ALL (subquery) means comparing with the maximum,', 'sal >= ALL (подзапрос) означает сравнение с максимумом,'),
          A(1, 'sal >= ANY (podzapytanie) oznacza porównanie z minimum,', 'sal >= ANY (subquery) means comparing with the minimum,', 'sal >= ANY (подзапрос) означает сравнение с минимумом,'),
          A(1, 'SOME i ANY to synonimy,', 'SOME and ANY are synonyms,', 'SOME и ANY — синонимы,'),
          A(0, 'ALL działa tylko w Oracle.', 'ALL works only in Oracle.', 'ALL работает только в Oracle.')],
      e: T('ALL/ANY działają w obu serwerach; tylko Oracle ma zagnieżdżone agregaty MAX(AVG(…)).', 'ALL/ANY work on both servers; only Oracle has nested aggregates MAX(AVG(…)).', 'ALL/ANY работают на обоих серверах; только в Oracle есть вложенные агрегаты MAX(AVG(…)).') },

    { t: 'dml',
      q: T('TRUNCATE TABLE:', 'TRUNCATE TABLE:', 'TRUNCATE TABLE:'),
      a: [A(1, 'należy do poleceń DDL,', 'belongs to DDL commands,', 'относится к командам DDL,'),
          A(0, 'w Oracle po ROLLBACK dane wracają,', 'in Oracle the data comes back after ROLLBACK,', 'в Oracle после ROLLBACK данные возвращаются,'),
          A(1, 'w MS SQL w transakcji można je wycofać,', 'in MS SQL it can be rolled back inside a transaction,', 'в MS SQL внутри транзакции его можно откатить,'),
          A(0, 'ma klauzulę WHERE.', 'has a WHERE clause.', 'имеет предложение WHERE.')],
      e: T('W Oracle DDL nie jest transakcyjne (dane znikają na zawsze); w MS SQL jest. TRUNCATE usuwa wszystkie wiersze.', 'In Oracle DDL is not transactional (data is gone for good); in MS SQL it is. TRUNCATE removes all rows.', 'В Oracle DDL не транзакционный (данные пропадают навсегда); в MS SQL — транзакционный. TRUNCATE удаляет все строки.') },

    { t: 'ddl',
      q: T('Akcje referencyjne przy DELETE:', 'Referential actions on DELETE:', 'Ссылочные действия при DELETE:'),
      a: [A(1, 'domyślna to NO ACTION (blokada usunięcia),', 'the default is NO ACTION (delete blocked),', 'по умолчанию NO ACTION (удаление блокируется),'),
          A(0, 'Oracle obsługuje ON DELETE SET DEFAULT,', 'Oracle supports ON DELETE SET DEFAULT,', 'Oracle поддерживает ON DELETE SET DEFAULT,'),
          A(1, 'ON DELETE CASCADE usuwa także wiersze podrzędne,', 'ON DELETE CASCADE also deletes child rows,', 'ON DELETE CASCADE удаляет и подчинённые строки,'),
          A(1, 'ON DELETE SET NULL wstawia NULL do klucza obcego.', 'ON DELETE SET NULL puts NULL into the foreign key.', 'ON DELETE SET NULL ставит NULL во внешний ключ.')],
      e: T('SET DEFAULT jest tylko w MS SQL.', 'SET DEFAULT exists only in MS SQL.', 'SET DEFAULT есть только в MS SQL.') },

    { t: 'ddl',
      q: T('Właściwość IDENTITY w MS SQL:', 'The IDENTITY property in MS SQL:', 'Свойство IDENTITY в MS SQL:'),
      a: [A(1, 'w INSERT pomijamy kolumnę z IDENTITY,', 'in INSERT we omit the IDENTITY column,', 'в INSERT столбец с IDENTITY опускаем,'),
          A(1, 'SCOPE_IDENTITY() zwraca ostatnią wartość z bieżącego zasięgu,', 'SCOPE_IDENTITY() returns the last value from the current scope,', 'SCOPE_IDENTITY() возвращает последнее значение в текущей области,'),
          A(0, 'tabela może mieć kilka kolumn IDENTITY,', 'a table can have several IDENTITY columns,', 'в таблице может быть несколько столбцов IDENTITY,'),
          A(1, 'IDENTITY(10, 10) daje 10, 20, 30, …', 'IDENTITY(10, 10) gives 10, 20, 30, …', 'IDENTITY(10, 10) даёт 10, 20, 30, …')],
      e: T('Najwyżej jedna kolumna IDENTITY na tabelę.', 'At most one IDENTITY column per table.', 'Не более одного столбца IDENTITY на таблицу.') },

    { t: 'views',
      q: T('Widoki (perspektywy):', 'Views:', 'Представления (views):'),
      a: [A(0, 'zwykły widok fizycznie przechowuje dane,', 'an ordinary view physically stores data,', 'обычное представление физически хранит данные,'),
          A(1, 'WITH CHECK OPTION nie pozwala zmienić wiersza tak, by wypadł z widoku,', 'WITH CHECK OPTION prevents changing a row so that it leaves the view,', 'WITH CHECK OPTION не даёт изменить строку так, чтобы она выпала из представления,'),
          A(0, 'przez widok z GROUP BY można wykonać UPDATE,', 'an UPDATE can be done through a view with GROUP BY,', 'через представление с GROUP BY можно сделать UPDATE,'),
          A(1, 'perspektywa zmaterializowana (Oracle) fizycznie przechowuje wynik.', 'a materialized view (Oracle) physically stores the result.', 'материализованное представление (Oracle) физически хранит результат.')],
      e: T('Widok to zapisany SELECT. DML przez widok wymaga m.in. braku GROUP BY, DISTINCT i jednej tabeli.', 'A view is a stored SELECT. DML through a view requires e.g. no GROUP BY, no DISTINCT and a single table.', 'Представление — сохранённый SELECT. DML через него требует отсутствия GROUP BY, DISTINCT и одной таблицы.') },

    { t: 'tsql-basics',
      q: T('Zmienne w T-SQL:', 'Variables in T-SQL:', 'Переменные в T-SQL:'),
      a: [A(1, 'nazwa zaczyna się od @,', 'the name starts with @,', 'имя начинается с @,'),
          A(1, 'niezainicjowana zmienna ma wartość NULL,', 'an uninitialised variable is NULL,', 'неинициализированная переменная равна NULL,'),
          A(0, 'SET może przypisać kilka zmiennych naraz,', 'SET can assign several variables at once,', 'SET может присвоить несколько переменных сразу,'),
          A(0, 'SELECT @x = kol FROM t zwracający wiele wierszy powoduje błąd.', 'SELECT @x = col FROM t returning many rows causes an error.', 'SELECT @x = col FROM t, возвращающий много строк, вызывает ошибку.')],
      e: T('SET — jedna zmienna. SELECT przypisuje wartość z ostatniego wiersza bez błędu.', 'SET — one variable. SELECT assigns the last row value without an error.', 'SET — одна переменная. SELECT присваивает значение последней строки без ошибки.') },

    { t: 'tsql-cursors',
      q: T('Kursory w T-SQL:', 'Cursors in T-SQL:', 'Курсоры в T-SQL:'),
      a: [A(1, 'FETCH zwykle występuje dwa razy: przed pętlą i na końcu pętli,', 'FETCH usually appears twice: before the loop and at the end of the loop,', 'FETCH обычно встречается дважды: перед циклом и в конце цикла,'),
          A(1, '@@FETCH_STATUS = 0 oznacza, że pobrano wiersz,', '@@FETCH_STATUS = 0 means a row was fetched,', '@@FETCH_STATUS = 0 означает, что строка получена,'),
          A(1, 'DEALLOCATE usuwa definicję kursora,', 'DEALLOCATE removes the cursor definition,', 'DEALLOCATE удаляет определение курсора,'),
          A(0, 'po CLOSE kursora nie da się ponownie otworzyć.', 'after CLOSE the cursor cannot be opened again.', 'после CLOSE курсор нельзя открыть снова.')],
      e: T('CLOSE zwalnia blokady i bufor, ale definicja zostaje — można znów OPEN.', 'CLOSE releases locks and the buffer, but the definition stays — you can OPEN again.', 'CLOSE освобождает блокировки и буфер, но определение остаётся — можно снова OPEN.') },

    { t: 'tsql-procedures',
      q: T('Zwracanie wyników z procedury T-SQL:', 'Returning results from a T-SQL procedure:', 'Возврат результатов из процедуры T-SQL:'),
      a: [A(1, 'RETURN może zwrócić tylko liczbę całkowitą,', 'RETURN can return only an integer,', 'RETURN может вернуть только целое число,'),
          A(1, 'parametr OUTPUT trzeba oznaczyć OUTPUT także przy wywołaniu,', 'an OUTPUT parameter must be marked OUTPUT in the call too,', 'параметр OUTPUT нужно пометить OUTPUT и при вызове,'),
          A(1, 'wynik SELECT (result set) też jest sposobem zwracania danych,', 'the SELECT result (result set) is also a way to return data,', 'результат SELECT (result set) — тоже способ вернуть данные,'),
          A(0, 'RETURN może zwrócić tekst (VARCHAR).', 'RETURN can return text (VARCHAR).', 'RETURN может вернуть текст (VARCHAR).')],
      e: T('Trzy sposoby: result set, OUTPUT, RETURN (tylko INT).', 'Three ways: result set, OUTPUT, RETURN (INT only).', 'Три способа: result set, OUTPUT, RETURN (только INT).') },

    { t: 'tsql-triggers',
      q: T('Wyzwalacze DML w T-SQL:', 'DML triggers in T-SQL:', 'DML-триггеры в T-SQL:'),
      a: [A(1, 'uruchamiają się raz na instrukcję, a nie dla każdego wiersza,', 'fire once per statement, not for each row,', 'срабатывают один раз на инструкцию, а не на каждую строку,'),
          A(1, 'przy UPDATE stare wartości są w deleted, nowe w inserted,', 'on UPDATE old values are in deleted, new ones in inserted,', 'при UPDATE старые значения в deleted, новые в inserted,'),
          A(0, 'tabele inserted i deleted można modyfikować,', 'the inserted and deleted tables can be modified,', 'таблицы inserted и deleted можно изменять,'),
          A(1, 'ROLLBACK w wyzwalaczu cofa instrukcję, która go uruchomiła.', 'ROLLBACK in a trigger undoes the statement that fired it.', 'ROLLBACK в триггере откатывает инструкцию, которая его вызвала.')],
      e: T('inserted/deleted są tylko do odczytu. Wyzwalacz działa po DML, ale w tej samej transakcji.', 'inserted/deleted are read-only. The trigger runs after the DML, but in the same transaction.', 'inserted/deleted только для чтения. Триггер работает после DML, но в той же транзакции.') },

    { t: 'tsql-triggers',
      q: T('RAISERROR i THROW:', 'RAISERROR and THROW:', 'RAISERROR и THROW:'),
      a: [A(1, 'RAISERROR z severity ≥ 11 w bloku TRY przenosi sterowanie do CATCH,', 'RAISERROR with severity ≥ 11 inside TRY moves control to CATCH,', 'RAISERROR с severity ≥ 11 в блоке TRY передаёт управление в CATCH,'),
          A(0, 'RAISERROR poza TRY zawsze przerywa wykonywanie kodu,', 'RAISERROR outside TRY always stops code execution,', 'RAISERROR вне TRY всегда прерывает выполнение,'),
          A(1, 'severity 10 to tylko komunikat (ostrzeżenie),', 'severity 10 is only a message (warning),', 'severity 10 — только сообщение (предупреждение),'),
          A(1, 'THROW działa jak błąd z severity 16.', 'THROW behaves like an error with severity 16.', 'THROW ведёт себя как ошибка с severity 16.')],
      e: T('Poza TRY RAISERROR nie przerywa — kolejne instrukcje się wykonają (stąd RETURN po RAISERROR).', 'Outside TRY RAISERROR does not stop — following statements still run (hence RETURN after RAISERROR).', 'Вне TRY RAISERROR не прерывает — следующие инструкции выполнятся (поэтому RETURN после RAISERROR).') },

    { t: 'plsql-basics',
      q: T('SELECT … INTO w PL/SQL:', 'SELECT … INTO in PL/SQL:', 'SELECT … INTO в PL/SQL:'),
      a: [A(1, 'gdy nie ma wiersza, podnosi NO_DATA_FOUND,', 'when there is no row it raises NO_DATA_FOUND,', 'если строки нет, возбуждает NO_DATA_FOUND,'),
          A(1, 'gdy jest wiele wierszy, podnosi TOO_MANY_ROWS,', 'when there are many rows it raises TOO_MANY_ROWS,', 'если строк много, возбуждает TOO_MANY_ROWS,'),
          A(0, 'gdy nie ma wiersza, zmienna zachowuje starą wartość,', 'when there is no row the variable keeps its old value,', 'если строки нет, переменная сохраняет старое значение,'),
          A(1, 'musi zwrócić dokładnie jeden wiersz.', 'must return exactly one row.', 'должен вернуть ровно одну строку.')],
      e: T('To ważna różnica względem T-SQL, gdzie brak wiersza nie jest błędem.', 'This is an important difference from T-SQL, where no row is not an error.', 'Важное отличие от T-SQL, где отсутствие строки — не ошибка.') },

    { t: 'plsql-basics',
      q: T('Składnia PL/SQL:', 'PL/SQL syntax:', 'Синтаксис PL/SQL:'),
      a: [A(0, 'wolno napisać IF EXISTS (SELECT …) THEN,', 'you may write IF EXISTS (SELECT …) THEN,', 'можно написать IF EXISTS (SELECT …) THEN,'),
          A(1, 'operatorem przypisania jest :=,', 'the assignment operator is :=,', 'оператор присваивания — :=,'),
          A(1, 'kolejne warunki zapisuje się słowem ELSIF,', 'further conditions are written with ELSIF,', 'следующие условия пишутся через ELSIF,'),
          A(1, 'DBMS_OUTPUT.PUT_LINE wypisuje tekst po SET SERVEROUTPUT ON.', 'DBMS_OUTPUT.PUT_LINE prints text after SET SERVEROUTPUT ON.', 'DBMS_OUTPUT.PUT_LINE выводит текст после SET SERVEROUTPUT ON.')],
      e: T('IF EXISTS to konstrukcja T-SQL. W PL/SQL: SELECT COUNT(*) INTO v … ; IF v > 0 THEN …', 'IF EXISTS is a T-SQL construct. In PL/SQL: SELECT COUNT(*) INTO v … ; IF v > 0 THEN …', 'IF EXISTS — конструкция T-SQL. В PL/SQL: SELECT COUNT(*) INTO v … ; IF v > 0 THEN …') },

    { t: 'plsql-cursors',
      q: T('Kursory w PL/SQL:', 'Cursors in PL/SQL:', 'Курсоры в PL/SQL:'),
      a: [A(1, 'EXIT WHEN k%NOTFOUND piszemy zaraz po FETCH,', 'EXIT WHEN k%NOTFOUND is written right after FETCH,', 'EXIT WHEN k%NOTFOUND пишут сразу после FETCH,'),
          A(1, 'pętla FOR r IN k sama otwiera i zamyka kursor,', 'the loop FOR r IN k opens and closes the cursor itself,', 'цикл FOR r IN k сам открывает и закрывает курсор,'),
          A(1, 'k%ROWCOUNT to liczba pobranych dotąd wierszy,', 'k%ROWCOUNT is the number of rows fetched so far,', 'k%ROWCOUNT — число уже полученных строк,'),
          A(0, 'kursor trzeba na końcu zwolnić poleceniem DEALLOCATE.', 'the cursor must be released at the end with DEALLOCATE.', 'курсор нужно в конце освободить командой DEALLOCATE.')],
      e: T('DEALLOCATE istnieje tylko w T-SQL. W PL/SQL wystarczy CLOSE (albo pętla FOR).', 'DEALLOCATE exists only in T-SQL. In PL/SQL CLOSE is enough (or a FOR loop).', 'DEALLOCATE есть только в T-SQL. В PL/SQL достаточно CLOSE (или цикла FOR).') },

    { t: 'plsql-procedures',
      q: T('Procedury i funkcje PL/SQL:', 'PL/SQL procedures and functions:', 'Процедуры и функции PL/SQL:'),
      a: [A(1, 'typy parametrów podaje się bez rozmiaru (np. VARCHAR2),', 'parameter types are given without size (e.g. VARCHAR2),', 'типы параметров указываются без размера (напр. VARCHAR2),'),
          A(0, 'parametrowi IN można przypisać nową wartość w procedurze,', 'an IN parameter can be assigned a new value inside the procedure,', 'параметру IN можно присвоить новое значение в процедуре,'),
          A(1, 'CREATE OR REPLACE zastępuje istniejący obiekt bez błędu,', 'CREATE OR REPLACE replaces an existing object without an error,', 'CREATE OR REPLACE заменяет существующий объект без ошибки,'),
          A(1, 'funkcja użyta w SELECT nie może wykonywać DML.', 'a function used in SELECT cannot perform DML.', 'функция, используемая в SELECT, не может выполнять DML.')],
      e: T('Parametr IN jest tylko do odczytu; do zwracania służą OUT i IN OUT.', 'An IN parameter is read-only; OUT and IN OUT are for returning values.', 'Параметр IN только для чтения; для возврата — OUT и IN OUT.') },

    { t: 'plsql-triggers',
      q: T('Wyzwalacze PL/SQL:', 'PL/SQL triggers:', 'Триггеры PL/SQL:'),
      a: [A(1, ':OLD i :NEW są dostępne w wyzwalaczach wierszowych (FOR EACH ROW),', ':OLD and :NEW are available in row-level (FOR EACH ROW) triggers,', ':OLD и :NEW доступны в строчных триггерах (FOR EACH ROW),'),
          A(0, 'w wyzwalaczu wolno wykonać COMMIT,', 'COMMIT is allowed in a trigger,', 'в триггере можно выполнить COMMIT,'),
          A(1, 'wyzwalacz wierszowy czytający własną tabelę może dać ORA-04091,', 'a row trigger reading its own table may raise ORA-04091,', 'строчный триггер, читающий свою таблицу, может дать ORA-04091,'),
          A(0, 'INSTEAD OF w Oracle można założyć na tabeli.', 'INSTEAD OF in Oracle can be defined on a table.', 'INSTEAD OF в Oracle можно создать на таблице.')],
      e: T('COMMIT/ROLLBACK są zabronione; INSTEAD OF w Oracle — tylko na widokach.', 'COMMIT/ROLLBACK are forbidden; INSTEAD OF in Oracle — only on views.', 'COMMIT/ROLLBACK запрещены; INSTEAD OF в Oracle — только на представлениях.') },

    { t: 'adm-indexes',
      q: T('Indeksy:', 'Indexes:', 'Индексы:'),
      a: [A(1, 'tabela może mieć tylko jeden indeks pogrupowany,', 'a table can have only one clustered index,', 'у таблицы может быть только один кластерный индекс,'),
          A(0, 'indeks złożony (job, sal) zostanie użyty dla samego WHERE sal = 1000,', 'a composite index (job, sal) will be used for WHERE sal = 1000 alone,', 'составной индекс (job, sal) будет использован для одного WHERE sal = 1000,'),
          A(1, 'indeks na kluczu obcym zwykle się opłaca,', 'an index on a foreign key usually pays off,', 'индекс по внешнему ключу обычно окупается,'),
          A(0, 'indeks na małej, często zmienianej tabeli zawsze przyspiesza pracę.', 'an index on a small, frequently changed table always speeds things up.', 'индекс на маленькой, часто изменяемой таблице всегда ускоряет работу.')],
      e: T('Indeks złożony działa, gdy zapytanie używa jego pierwszej kolumny. Na małych i często zmienianych tabelach indeksy raczej szkodzą.', 'A composite index works when the query uses its first column. On small, often-changed tables indexes rather hurt.', 'Составной индекс работает, если запрос использует его первый столбец. На маленьких и часто изменяемых таблицах индексы скорее вредят.') },

    { t: 'adm-indexes',
      q: T('Plan wykonania zapytania:', 'The query execution plan:', 'План выполнения запроса:'),
      a: [A(1, 'Table Scan oznacza odczyt całej tabeli,', 'Table Scan means reading the whole table,', 'Table Scan означает чтение всей таблицы,'),
          A(1, 'Index Seek oznacza użycie indeksu do znalezienia konkretnych wierszy,', 'Index Seek means using an index to find specific rows,', 'Index Seek означает использование индекса для поиска конкретных строк,'),
          A(0, 'Index Scan zawsze oznacza najlepszy możliwy plan,', 'Index Scan always means the best possible plan,', 'Index Scan всегда означает лучший возможный план,'),
          A(1, 'warunek WHERE sal * 12 = 12000 może uniemożliwić użycie indeksu na sal.', 'the condition WHERE sal * 12 = 12000 may prevent using the index on sal.', 'условие WHERE sal * 12 = 12000 может помешать использовать индекс по sal.')],
      e: T('Index Scan to przejście całego indeksu — przy zapytaniu z WHERE sugeruje, że warto pomyśleć o innym indeksie.', 'Index Scan reads the whole index — with a WHERE query it suggests considering another index.', 'Index Scan — проход всего индекса; при запросе с WHERE стоит подумать о другом индексе.') },

    { t: 'adm-transactions',
      q: T('Poziomy izolacji:', 'Isolation levels:', 'Уровни изоляции:'),
      a: [A(1, 'domyślnym poziomem jest READ COMMITTED,', 'the default level is READ COMMITTED,', 'уровень по умолчанию — READ COMMITTED,'),
          A(1, 'READ UNCOMMITTED dopuszcza brudny odczyt,', 'READ UNCOMMITTED allows dirty reads,', 'READ UNCOMMITTED допускает грязное чтение,'),
          A(0, 'REPEATABLE READ chroni przed fantomami,', 'REPEATABLE READ protects against phantoms,', 'REPEATABLE READ защищает от фантомов,'),
          A(1, 'SERIALIZABLE usuwa wszystkie trzy anomalie.', 'SERIALIZABLE removes all three anomalies.', 'SERIALIZABLE устраняет все три аномалии.')],
      e: T('Fantomy usuwa dopiero SERIALIZABLE.', 'Only SERIALIZABLE removes phantoms.', 'Фантомы устраняет только SERIALIZABLE.') },

    { t: 'adm-transactions',
      q: T('Skrót ACID oznacza:', 'The acronym ACID stands for:', 'Аббревиатура ACID означает:'),
      a: [A(1, 'A — atomowość (wszystko albo nic),', 'A — atomicity (all or nothing),', 'A — атомарность (всё или ничего),'),
          A(0, 'C — współbieżność (concurrency),', 'C — concurrency,', 'C — параллелизм (concurrency),'),
          A(1, 'I — izolacja,', 'I — isolation,', 'I — изоляция,'),
          A(1, 'D — trwałość.', 'D — durability.', 'D — долговечность (надёжность).')],
      e: T('C to spójność (consistency).', 'C is consistency.', 'C — согласованность (consistency).') },

    { t: 'adm-backup-security',
      q: T('Kopie zapasowe w MS SQL:', 'Backups in MS SQL:', 'Резервные копии в MS SQL:'),
      a: [A(1, 'kopia różnicowa zawiera zmiany od ostatniej kopii pełnej,', 'a differential backup contains changes since the last full backup,', 'разностная копия содержит изменения с последней полной,'),
          A(1, 'kolejność odtwarzania: pełna → ostatnia różnicowa → kopie dziennika po kolei,', 'restore order: full → last differential → log backups in order,', 'порядок восстановления: полная → последняя разностная → копии журнала по порядку,'),
          A(0, 'opcję NORECOVERY stosujemy przy odtwarzaniu ostatniej kopii,', 'NORECOVERY is used when restoring the last backup,', 'опцию NORECOVERY применяют при восстановлении последней копии,'),
          A(1, 'kopia dziennika czyści dziennik transakcji.', 'a log backup truncates the transaction log.', 'копия журнала очищает журнал транзакций.')],
      e: T('NORECOVERY — dla wszystkich kopii poza ostatnią; ostatnia z RECOVERY.', 'NORECOVERY — for all backups except the last; the last one WITH RECOVERY.', 'NORECOVERY — для всех копий, кроме последней; последняя с RECOVERY.') },

    { t: 'adm-backup-security',
      q: T('Uprawnienia:', 'Permissions:', 'Права доступа:'),
      a: [A(1, 'DENY dla roli + GRANT dla użytkownika z tej roli → operacja zabroniona,', 'DENY on a role + GRANT on a user in that role → the operation is denied,', 'DENY для роли + GRANT пользователю из этой роли → операция запрещена,'),
          A(0, 'DENY jest dostępne także w Oracle,', 'DENY is also available in Oracle,', 'DENY доступен и в Oracle,'),
          A(1, 'w MS SQL login działa na poziomie serwera, a user na poziomie bazy,', 'in MS SQL a login works at the server level and a user at the database level,', 'в MS SQL логин — уровень сервера, пользователь — уровень базы,'),
          A(1, 'rola grupuje uprawnienia dla wielu użytkowników.', 'a role groups permissions for many users.', 'роль группирует права для многих пользователей.')],
      e: T('DENY (tylko MS SQL) jest silniejsze niż GRANT.', 'DENY (MS SQL only) is stronger than GRANT.', 'DENY (только MS SQL) сильнее GRANT.') },

    { t: 'adm-server',
      q: T('Budowa serwera (MS SQL):', 'Server structure (MS SQL):', 'Устройство сервера (MS SQL):'),
      a: [A(1, 'pierwszy plik danych ma rozszerzenie .mdf, dziennik — .ldf,', 'the first data file has the .mdf extension, the log — .ldf,', 'первый файл данных имеет расширение .mdf, журнал — .ldf,'),
          A(1, 'WAL: zapis do dziennika następuje przed zatwierdzeniem transakcji,', 'WAL: writing to the log happens before the transaction is committed,', 'WAL: запись в журнал происходит до подтверждения транзакции,'),
          A(1, 'strona ma 8 KB,', 'a page is 8 KB,', 'страница имеет размер 8 КБ,'),
          A(0, 'extent to 16 stron.', 'an extent is 16 pages.', 'экстент — это 16 страниц.')],
      e: T('Extent = 8 stron (64 KB).', 'An extent = 8 pages (64 KB).', 'Экстент = 8 страниц (64 КБ).') },

    { t: 'distributed',
      q: T('Bazy rozproszone:', 'Distributed databases:', 'Распределённые базы данных:'),
      a: [A(1, 'w 2PC koordynator w pierwszej fazie wysyła „prepare”,', 'in 2PC the coordinator sends "prepare" in the first phase,', 'в 2PC координатор в первой фазе отправляет «prepare»,'),
          A(1, 'jeśli choć jeden węzeł odpowie „no”, transakcja jest wycofywana,', 'if at least one node answers "no", the transaction is aborted,', 'если хотя бы один узел ответит «no», транзакция откатывается,'),
          A(1, 'replikacja scalająca pozwala zmieniać dane u subskrybentów,', 'merge replication allows changing data at subscribers,', 'репликация слиянием позволяет менять данные у подписчиков,'),
          A(0, 'replikacja migawkowa przesyła tylko zmiany.', 'snapshot replication sends only the changes.', 'моментальная репликация передаёт только изменения.')],
      e: T('Migawkowa przesyła za każdym razem całość; zmiany z logu przesyła transakcyjna.', 'Snapshot replication sends everything each time; transactional replication sends changes from the log.', 'Моментальная передаёт каждый раз всё; изменения из журнала передаёт транзакционная.') },

    { t: 'warehouses',
      q: T('Hurtownia danych wg Inmona jest:', 'According to Inmon a data warehouse is:', 'По Инмону хранилище данных:'),
      a: [A(1, 'nieulotna,', 'nonvolatile,', 'неизменяемое (nonvolatile),'),
          A(1, 'zorientowana na temat,', 'subject-oriented,', 'предметно-ориентированное,'),
          A(1, 'zintegrowana i zróżnicowana czasowo,', 'integrated and time-variant,', 'интегрированное и зависящее от времени,'),
          A(0, 'zoptymalizowana pod częste UPDATE pojedynczych rekordów.', 'optimised for frequent UPDATEs of single records.', 'оптимизировано под частые UPDATE отдельных записей.')],
      e: T('Częste zmiany pojedynczych wierszy to cecha OLTP; hurtownia to głównie odczyt i ładowanie wsadowe.', 'Frequent single-row changes are OLTP; a warehouse is mostly reads and batch loading.', 'Частые изменения отдельных строк — это OLTP; хранилище — в основном чтение и пакетная загрузка.') },

    { t: 'warehouses',
      q: T('Schemat gwiazdy:', 'The star schema:', 'Схема «звезда»:'),
      a: [A(1, 'tabela faktów zawiera miary i klucze obce do wymiarów,', 'the fact table contains measures and foreign keys to dimensions,', 'таблица фактов содержит меры и внешние ключи к измерениям,'),
          A(0, 'tabele wymiarów są w nim znormalizowane,', 'dimension tables in it are normalized,', 'таблицы измерений в ней нормализованы,'),
          A(1, 'płatek śniegu wydziela hierarchie wymiarów do osobnych tabel,', 'a snowflake moves dimension hierarchies to separate tables,', '«снежинка» выносит иерархии измерений в отдельные таблицы,'),
          A(1, 'miary powinny być (przynajmniej częściowo) sumowalne.', 'measures should be (at least partly) additive.', 'меры должны быть (хотя бы частично) суммируемыми.')],
      e: T('W gwieździe wymiary są nieznormalizowane.', 'In a star the dimensions are denormalized.', 'В «звезде» измерения ненормализованы.') },

    { t: 'object-lob',
      q: T('Obiekty i LOB w Oracle:', 'Objects and LOBs in Oracle:', 'Объекты и LOB в Oracle:'),
      a: [A(1, 'CLOB służy do dużych tekstów,', 'CLOB is for large texts,', 'CLOB служит для больших текстов,'),
          A(1, 'BLOB służy do danych binarnych,', 'BLOB is for binary data,', 'BLOB служит для двоичных данных,'),
          A(1, 'EMPTY_CLOB() inicjalizuje pusty LOB, do którego można pisać,', 'EMPTY_CLOB() initialises an empty LOB that can be written to,', 'EMPTY_CLOB() инициализирует пустой LOB, в который можно писать,'),
          A(0, 'VARRAY to tablica bez limitu rozmiaru.', 'VARRAY is an array without a size limit.', 'VARRAY — массив без ограничения размера.')],
      e: T('VARRAY(n) ma maksymalny rozmiar n.', 'VARRAY(n) has a maximum size n.', 'VARRAY(n) имеет максимальный размер n.') },

    { t: 'plsql-advanced',
      q: T('IDENTITY w Oracle (12c+):', 'IDENTITY in Oracle (12c+):', 'IDENTITY в Oracle (12c+):'),
      a: [A(1, 'GENERATED ALWAYS nie pozwala wpisać własnej wartości,', 'GENERATED ALWAYS does not allow inserting your own value,', 'GENERATED ALWAYS не позволяет вставить своё значение,'),
          A(1, 'BY DEFAULT ON NULL generuje wartość także, gdy podamy NULL,', 'BY DEFAULT ON NULL also generates a value when NULL is given,', 'BY DEFAULT ON NULL генерирует значение и когда передан NULL,'),
          A(0, 'Oracle ma funkcję SCOPE_IDENTITY(),', 'Oracle has a SCOPE_IDENTITY() function,', 'в Oracle есть функция SCOPE_IDENTITY(),'),
          A(1, 'w tabeli może być tylko jedna kolumna IDENTITY.', 'a table can have only one IDENTITY column.', 'в таблице может быть только один столбец IDENTITY.')],
      e: T('SCOPE_IDENTITY() jest w MS SQL. W Oracle ostatnią wartość łatwo odczytać z sekwencji (CURRVAL).', 'SCOPE_IDENTITY() is in MS SQL. In Oracle the last value is easy to read from a sequence (CURRVAL).', 'SCOPE_IDENTITY() есть в MS SQL. В Oracle последнее значение легко взять из последовательности (CURRVAL).') }
  ];
})(window.SBD);
